name: Compile Examples

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  unittests-linux-generic:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/modm-ext/modm-build-avr:latest

    strategy:
      fail-fast: false
      matrix:
        standard: [ c++17, c++20 ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check environment
        run: |
          env
          which avr-g++
          avr-g++ --version

      - name: Compile Examples
        run: |
          for example in $(find examples/ | grep Makefile); do
            (cd $(dirname $example) && make -j4 STD=${{ matrix.standard }})
          done
